package com.attendance.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

/**
 * Request payload for employee check-in.
 * Deserialised from JSON by Jackson via {@code @RequestBody}.
 */
public class CheckInRequest {

    /** GPS latitude — required for geofencing (skipped on approved WFH days). */
    @NotNull(message = "Latitude is required for check-in")
    private Double latitude;

    /** GPS longitude — required for geofencing (skipped on approved WFH days). */
    @NotNull(message = "Longitude is required for check-in")
    private Double longitude;

    /** Optional daily QR session token generated by the admin dashboard. */
    private String qrToken;

    /**
     * JSON-serialised face descriptor string from face-api.js, e.g. "[0.1, -0.3, ...]".
     * Must be a String — do not pass a raw JSON array object.
     */
    @NotBlank(message = "Face biometric descriptor is required for check-in")
    private String faceDescriptor;

    /** Base64-encoded selfie image captured at check-in — stored as LONGTEXT for audit. */
    @NotBlank(message = "Selfie image is required for check-in")
    private String selfieBase64;

    /** Resolved human-readable address from browser Geocoding API (optional). */
    private String address;

    public CheckInRequest() {}

    public Double getLatitude() { return latitude; }
    public void setLatitude(Double latitude) { this.latitude = latitude; }

    public Double getLongitude() { return longitude; }
    public void setLongitude(Double longitude) { this.longitude = longitude; }

    public String getQrToken() { return qrToken; }
    public void setQrToken(String qrToken) { this.qrToken = qrToken; }

    public String getFaceDescriptor() { return faceDescriptor; }
    public void setFaceDescriptor(String faceDescriptor) { this.faceDescriptor = faceDescriptor; }

    public String getSelfieBase64() { return selfieBase64; }
    public void setSelfieBase64(String selfieBase64) { this.selfieBase64 = selfieBase64; }

    public String getAddress() { return address; }
    public void setAddress(String address) { this.address = address; }

    @Override
    public String toString() {
        return "CheckInRequest{" +
                "latitude=" + latitude +
                ", longitude=" + longitude +
                ", qrToken='" + qrToken + '\'' +
                ", faceDescriptor='[DESCRIPTOR]'" +
                ", selfieBase64='[BASE64_IMAGE]'" +
                ", address='" + address + '\'' +
                '}';
    }
}

